#!/bin/sh

set -ex

ROOT="$(git rev-parse --show-toplevel)"

cd "$ROOT"

dbfs cp --overwrite echo.py dbfs:/user/gabor.ratky/echo.py
dbfs cp --overwrite dist/echo-1.0.0-py3-none-any.whl dbfs:/FileStore/wheel/echo-1.0.0-py3-none-any.whl